### PR TITLE
Config files updated

### PR DESCRIPTION
**Pull request by chrisblossom**
* Added .editorconfig for hassle-free editor spacing/tabs
* .gitignore - Added Intellij and VS Code's project files
* Fixed npmrc/yarnrc's save exact option
* Added [wallaby.js](https://wallabyjs.com/) config

### CODE REVIEW

**Comment by gpbl** [comment]
Thanks for this PR! I'm sorry – I won't add editor specific settings to the repo.

**Comment by chrisblossom** [comment]
Which editor specific things are you referring to?

**Comment by gpbl** [comment]
All your changes but the save exact option :)

**Comment by chrisblossom** [comment]
Adding the ``.editorconfig`` and additions to ``.gitignore`` makes it much easier for people to contribute to your repository.

All major editors support ``.editorconfig``. For example my editor is set to use 4 spaces by default, but with an ``.editorconfig`` in the project, it will automatically switch to 2.

The ``.gitignore`` just makes sure VS Code and Intellij do not commit their editor created files.

Both of these are very typical for a project to have.

Would you accept the PR with all changes but the ``wallaby.js`` config?

**Comment by gpbl** [comment]
I follow my rules to keep my repos easier to maintain :)
 
- I don't add to .gitignore things that are not related to the repo
- Code formatting should be managed by the linter or prettier
- I don't like too many .dotfiles

I don't know what is wallaby.js and which benefits it would add to this module.

**Comment by chrisblossom** [comment]
Okay fair enough. I'll resend the PR with the yarnrc and npmrc fixes. Prettier PR incoming too

**Comment by gpbl** [comment]
Awesome! Thanks for understanding! 🙏

**Comment by chrisblossom** [comment]
Just another note, ``.editorconfig`` makes it easier to edit files but should be managed, as you said, by eslint / prettier. It is just annoying when you are working with a project and pressing enter messes with spacing etc.

**Pull request closed without merging**
